### ISSUE TITLE
HttpRequestUrlEnricher gives "Request is not available in this context" exception

### ISSUE THREAD

**Issue by liviriniu** [serilog-web/classic#67] opened 2020-04-17 16:57 UTC
I am currently using SerilogWeb.Classic v5.0.56 in a legacy webforms website.
After I decided to enable SelfLog, I found that adding log entries from the `Application_Start` in `Global.asax` while enriching with `HttpRequestUrl` chained to `new LoggerConfiguration()` throws the following exception
```C#
2020-04-17T16:29:46.1743072Z Exception System.Web.HttpException (0x80004005): Request is not available in this context
   at System.Web.HttpContext.get_Request()
   at SerilogWeb.Classic.Enrichers.HttpRequestUrlEnricher.Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
   at Serilog.Core.Enrichers.SafeAggregateEnricher.Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory) caught while enriching Serilog.Events.LogEvent with SerilogWeb.Classic.Enrichers.HttpRequestUrlEnricher.
```

'This well known exception raises its fancy head again', I told myself. So, I've looked into `HttpContextCurrent.cs` and `HttpRequestUrlEnricher.cs`.

I think that replacing `if (HttpContext.Current?.Request?.Url == null)` with `if (HttpContextCurrent.Request?.Url == null)` would fix it.

_I am new to github. If I make mistakes please forgive a newbie, I'm learning/discovering :)_

**PS**: Also I looked through the other files in the project and found no other instance of `Request` being accessed outside project's `HttpContextCurrent`. I was thinking of renaming this to help against any future confusion with `HttpContext.Current`.

**Comment by tsimbalar** [comment] 2020-04-19 09:07
Hi @liviriniu  ,

thanks for the report ! 

Indeed, your intuition seems about right, and it looks like this is an issue similar to the one reported in https://github.com/serilog-web/classic/issues/1 and fixed in https://github.com/serilog-web/classic/pull/66 , but for another Enricher.

The root cause is that `HttpContext.Current.Request` throws when called outside the context of a request (for instance in `App_Start`), and this is why we had this `HttpContextCurrent` that returned `null` in that case instead.

How would you feel about doing opening a Pull Request for this fix ? I'm happy to help you along the way of course ! 

(I don't have access to a Windows machine lately so it could take some time until I take the time to do it myself)

Thanks !

**Comment by liviriniu** [comment] 2020-04-19 13:16
My pleasure to help, @tsimbalar 

I also encountered the problem in my current project and it seems that the only decent way is to centralize it like that.
Yes, I was thinking of doing just that but I thought to get in touch with you beforehand. I'll see to it today/tomorrow, while it's a fork I don't see why to worry of breaking anything.

I do have a small list of nit-picks & proposals, built along the way as I studied/implemented logging. Currently I'm past a deadline with notifications by email/sms with Quartz.net as basis for a workflow, but I would _certainly_ like to contribute when I'll get disencumbered (also I have here created and in-use a custom enricher `SubmittedFormDataEnricher` inspired by the work you guys did and I would like to show it to you in the future after it's matured. Maybe could be a useful addition?).
Serilog & friends really help me cut it through troubleshooting/pin-point bugs, I want to help back.

**Comment by liviriniu** [comment] 2020-04-20 14:23
@tsimbalar  I'll delete this after we get in touch on IM private chat as to not pollute here. I'm eager to complete this 8D but have some doubts on hitting the "Create pull request" button

**Comment by tsimbalar** [comment] 2020-04-20 19:09
You can create the PR, no worries, this cannot break anything :) 

And it will give a good place for us to leave comments inline with the code.

**Comment by liviriniu** [comment] 2020-04-20 20:12
Ah, alright then!
Reading GitHub help, I worried about needing a topic branch for the pull request if the project is of type "shared repository model" but I think it's not. Didn't managed to clarify this. I'll create the PR. Thanks

**Comment by tsimbalar** [comment] 2020-04-21 07:20
yes, usually, you would create a branch in your fork .... but merging from your master is also ok (from our side at least. It might problematic for you if you need to start working on different changes on your fork though, and then you would want to create a branch)

**Comment by tsimbalar** [comment] 2020-04-21 07:22
PR #68 is merged and should fix it.

It should appear shortly in Nuget with version v5.0.58 -  https://www.nuget.org/packages/SerilogWeb.Classic/5.0.58 .

Thanks @liviriniu  👍

**Closed as completed** 2020-04-21 07:24 UTC
